# Generated by Django 4.1.6 on 2023-02-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memlinkto_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapping',
            name='short_url',
            field=models.CharField(db_index=True, max_length=1000),
        ),
    ]
