# Generated by Django 4.1.6 on 2023-02-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memlinkto_app', '0002_alter_urlmapping_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapping',
            name='short_url',
            field=models.CharField(db_index=True, max_length=1000, unique=True),
        ),
    ]
