# Generated by Django 4.1.6 on 2023-03-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memlinkto_app', '0003_alter_urlmapping_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapping',
            name='long_url',
            field=models.CharField(db_index=True, max_length=10000),
        ),
    ]
